Removes last traces of SoftLayer and vCloud
PR 854 missed a couple of references to vCloud and SoftLayer docs,
causing the following failure in CI:

==========
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /tmp/build/91af2daf/docroot
ERROR   -  File not found: /tmp/build/91af2daf/docs/content/softlayer-cpi.md
ERROR   -  Error building page softlayer-cpi.md
Traceback (most recent call last):
.....
IOError: [Errno 2] No such file or directory: '/tmp/build/91af2daf/docs/content/softlayer-cpi.md'
==========

This commit removes the reference to softlayer-cpi.md, and speculatively
removes the reference to vcloud-cpi.md... expecting that CI will fail in
the same way if we don't remove it, too.

Signed-off-by: Nitin Ravindran <nitin.ravindran@broadcom.com>